// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMl1JxNPxIrIMgsRFxeYL-taHlmxyD20g',
    appId: '1:11261907467:web:8ddcb144ee7a77e36f6d0e',
    messagingSenderId: '11261907467',
    projectId: 'bcwallet-29037',
    authDomain: 'bcwallet-29037.firebaseapp.com',
    storageBucket: 'bcwallet-29037.appspot.com',
    measurementId: 'G-TG8WXZRM46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFvlNhl-5uhq2pRmc9nyaw5fGAf3VMXIc',
    appId: '1:11261907467:android:83bf0eae10f8cfb56f6d0e',
    messagingSenderId: '11261907467',
    projectId: 'bcwallet-29037',
    storageBucket: 'bcwallet-29037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoKesm8PMxUhxmpix0DN7oqTVZdmcw0JE',
    appId: '1:11261907467:ios:747cb525829fee726f6d0e',
    messagingSenderId: '11261907467',
    projectId: 'bcwallet-29037',
    storageBucket: 'bcwallet-29037.appspot.com',
    iosBundleId: 'com.example.bcwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoKesm8PMxUhxmpix0DN7oqTVZdmcw0JE',
    appId: '1:11261907467:ios:747cb525829fee726f6d0e',
    messagingSenderId: '11261907467',
    projectId: 'bcwallet-29037',
    storageBucket: 'bcwallet-29037.appspot.com',
    iosBundleId: 'com.example.bcwallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMl1JxNPxIrIMgsRFxeYL-taHlmxyD20g',
    appId: '1:11261907467:web:21300dce4141424a6f6d0e',
    messagingSenderId: '11261907467',
    projectId: 'bcwallet-29037',
    authDomain: 'bcwallet-29037.firebaseapp.com',
    storageBucket: 'bcwallet-29037.appspot.com',
    measurementId: 'G-LJYQKFYKDZ',
  );
}
